### ISSUE TITLE
[QUESTION] Stale Branches noch benötigt?

### ISSUE THREAD

**Issue by lumaghg** [projekt-fitnessapp/backend#107]
Falls Ihr die ganzen Branches, die zuletzt im Oktober benutzt wurden, nicht mehr braucht, könntet Ihr die mal aufräumen / könnten Fynn und Ich die mal aufräumen. 17 Branches erscheint mir etwas viel :)

**Comment by HaseFlrn** [comment]
Jetzt sinds weniger :P
