### ISSUE TITLE
[BUG] GET TrainingPlan klappt Exercises nicht aus

### ISSUE THREAD

**Issue by juengeja** [projekt-fitnessapp/backend#115]
**Was ist passiert:**
Exercises werden bei GET TrainingPlan nicht vollständig ausgeklappt

**Was sollte passieren:**
Entweder sollten die Exercises vollständig ausgeklappt werden, oder die Doku sollte angepasst werden.

**Wie kann der Fehler reproduziert werden:**
GET TrainingPlan

**Weitere Anmerkungen:**

**Comment by steffenhls** [comment]
Habs mir angeschaut. Aktuell wird es nicht genutzt. Um für meine View alle Pläne inkl Tage und Übungen zu laden nutze ich /myPlans. Maik gibt in seiner View nur ein Trainingstagnamen an und für die Navigation ins Tracking eine trainingsplan id und Matthias bastelt sich daraus eine Session. Denke das ändert sich auch eher nicht. Falls das einfach zu beheben wäre, dann gerne aber würde euch intern eher eine niedrige prio vorschlagen
