### ISSUE TITLE
[FEATURE] Ping Route für das Monitoring

### ISSUE THREAD

**Issue by lumaghg** [projekt-fitnessapp/backend#23]
**Wie ist es aktuell:**
Es gibt keine Ping Route um zu prüfen, ob der Container läuft
**Wie sollte es sein:**
Es gibt eine Ping Route um zu prüfen, ob der Container läuft
**Zusätzliche Anmerkungen:**
am besten unter /ping

**Comment by HaseFlrn** [comment]
@lumaghg: Welche response erwartest du?
- Statuscode 200 und etwas im body?
  - Was soll in den body?
- Statuscode 204 und kein body?

**Comment by lumaghg** [comment]
Gerne 200
Body : 
{ msg: "pong" }
Danke schonmal :)
