### ISSUE TITLE
[FEATURE] trainingDay exercises

### ISSUE THREAD

**Issue by steffenhls** [projekt-fitnessapp/backend#38]
**Wie ist es aktuell:**
Aktuell bekomme ich nur die id von der exercise und müsste dann diese nochmal anfragen.

**Wie sollte es sein:**
Es wäre super, wenn mir die Daten zu der Übung schon mitgegeben werden würde.

**Zusätzliche Anmerkungen:**
Wenn es nicht möglich wäre, dass zeitnah umzusetzen, bitte Bescheid geben, damit ich den Umweg über die IDs gehe.

GaLiGrü und Dankeschön

**Comment by juengeja** [comment]
Hi Nandini, hier müsstest du in deine TrainingDay Route ein populate einfügen, damit statt der Ids direkt die Objekte gezogen werden. Kannst du das direkt mit einbauen?

**Comment by Nandinihlg** [comment]
Hey, habe das gerade erst gesehen. Ja das kann ich machen.

Liebe Grüße

Jannis Jüngert ***@***.***> schrieb am So. 16. Okt. 2022 um
15:37:

**Comment by HaseFlrn** [comment]
Ist teil von [Issue 17](https://github.com/projekt-fitnessapp/backend/issues/17)
