### ISSUE TITLE
[BUG] Sortierung der Trainingspläne

### ISSUE THREAD

**Issue by steffenhls** [projekt-fitnessapp/backend#97]
Siehe https://github.com/projekt-fitnessapp/frontend/issues/47

Habe das jetzt ausgetestet und denke das liegt eher in eurer Expertise.
Ich gebe den Trainingsplan mit der richtigen Reihenfolge der Trainingstage mit, aber beim Aktualisieren der Daten ändert sich tw. die Reihenfolge. Vielleicht könnte da ja jemand von euch drüber gucken, danke.

**Comment by juengeja** [comment]
Tritt das nur für PUT auf? oder auch schon beim Anlegen mit POST? @steffenhls

**Comment by steffenhls** [comment]
> Tritt das nur für PUT auf? oder auch schon beim Anlegen mit POST? @steffenhls 

Soweit ich weiß nur beim aktualisieren, beim erstellen hab ich das noch nicht wahrgenommen

**Comment by juengeja** [comment]
> > Tritt das nur für PUT auf? oder auch schon beim Anlegen mit POST? @steffenhls
> 
> Soweit ich weiß nur beim aktualisieren, beim erstellen hab ich das noch nicht wahrgenommen

Alles klar, ich schaue es mir an.

**Comment by HaseFlrn** [comment]
Nach dem Update werden die Array-Elemente vertauscht. Dann bleibt das bis zum nächsten Update persistent.
